# Generated by Django 3.2.5 on 2021-11-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20211130_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='products',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='products',
            field=models.ManyToManyField(related_name='watched_by', to='auctions.Listing'),
        ),
        migrations.DeleteModel(
            name='UserWatchlist',
        ),
    ]
