# Generated by Django 3.2.5 on 2021-12-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20211130_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Generic', 'Generics'), ('Fashion', 'Fashion'), ('Toys', 'Toys'), ('Electronics', 'Electronics'), ('Home', 'Home'), ('Pets', 'Pets'), ('Cool Stuff', 'Cool Stuff'), ('Food', 'Food'), ('Books', 'Books')], max_length=16),
        ),
    ]
