# Generated by Django 3.2.5 on 2021-12-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='watched_by', to='auctions.Listing'),
        ),
    ]
